name: Playwright only Linux

on:
  # push:
  #   branches: ['deploy']
  workflow_dispatch:

jobs:
  e2e_test:
    name: 'Playwright Linux Docker Container'
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    container:
      image: mcr.microsoft.com/playwright:v1.30.0
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-report/
          retention-days: 30
